### ISSUE TITLE
Allow filtering of cookie flags, which enables setting of samesite

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#164]
Currently, it's not possible to set the "samesite" attribute on a cookie (or indeed, to do any filtering of what is set). It'd be useful generally to have a filter in `cocart_setcookie()` to allow arbitrary changing of the cookie options.

By changing the parameter style for `setcookie()`, it becomes possible to allow "samesite" to be set.

**Comment by seb86** [comment]
Done

**Comment by sdevogel** [comment]
Hi, looking into the changelogs I see a filter is added to added options to the cookies. Im looking into a way of setting the "samesite" to "none" so the cookies can be set since the admin is on a different domain.

How would you add the option with the cocart_set_cookie_options filter?
Thanks in advance!
