### ISSUE TITLE
Session conflict with WPML

### ISSUE THREAD

**Issue by harishksoft** [co-cart/co-cart#268]
I'm using the free version of cocart and when activating wpml woocommerce multilingual plugin an error showing like this "Error message: Uncaught TypeError: Argument 1 passed to WCML\User\Store\WcSession::__construct() must be an instance of WC_Session, instance of CoCart_Session_Handler given" and frontend of the site not loading. how to solve this?

**Comment by seb86** [comment]
@harishksoft Can you please test the [latest release candidate](https://cocart.dev/cocart-lite-v3-1-release-candidate-4/) of CoCart and see if you are able to replicate the error.

**Comment by harishksoft** [comment]
> 
> 
> @harishksoft Can you please test the [latest release candidate](https://cocart.dev/cocart-lite-v3-1-release-candidate-4/) of CoCart and see if you are able to replicate the error.

the error not showing anymore.. I think it's fixed now. let me check in detail and get back. once again thank you so much for the plugin and your support @seb86

**Comment by harishksoft** [comment]
![image](https://user-images.githubusercontent.com/27539252/133962428-6d5caae1-c363-4f46-9965-1c493e8283a5.png)
@seb86 this issue is showing in my error.log file.

**Comment by harishksoft** [comment]
> 
> 
> This latest error log you have shared does not specify a file and line number to which it's referring too. Not sure how I can help on this issue at this time @harishksoft

its common error i think.. even in error log not showing any particular page or line number

**Comment by harishksoft** [comment]
> 
> 
> @harishksoft Can you please test the [latest release candidate](https://cocart.dev/cocart-lite-v3-1-release-candidate-4/) of CoCart and see if you are able to replicate the error.

I have installed and found the following issues :
1. Can't add both variable and simple products to the cart
2. when refreshing the get cart API, sometimes items auto removing.

**Comment by seb86** [comment]
A little difficult to help if details are redacted but WPML is not supported so it would make sense if items are automatically removed when changing language as the cart is not in sync.

Can you please check your issue are not related to the following issues: https://github.com/co-cart/co-cart/issues/269 https://github.com/co-cart/co-cart/issues/270

**Comment by harishksoft** [comment]
> 
> 
> A little difficult to help if details are redacted but WPML is not supported so it would make sense if items are automatically removed when changing language as the cart is not in sync.
> 
> Can you please check your issue are not related to the following issues: #269 #270

actually, I didn't change the language. I just tried to add items through the API and view them through the front end of the website. as seen in the above screenshot, it shows product added to cart, but not showing in the item array.. and when refreshing the website it says item removed from the cart. also getting the get_cart function is deprecated too.. this was working fine with the previous version, but when I installed wpml and session start conflicting.

**Comment by seb86** [comment]
Started a [discussion for supporting plugins like WPML](https://github.com/co-cart/co-cart/discussions/350) and invited the WPML developers to join. https://twitter.com/sebd86/status/1557074134345125888

**Comment by Biont** [comment]
Hello everyone. We are facing very similar problems, though not related to WPML. I think this issue is worth discussing at its root, but if you prefer to keep this issue focussed on WPLM, I will happily create a new one.

Anyway, going back to the original error message:
 >`Uncaught TypeError: Argument 1 passed to <FOO> must be an instance of WC_Session, instance of CoCart_Session_Handler given`

...it seems that in recent releases, you made `CoCart_Session_Handler` inherit from `WC_Session` so that specific problem seems solved.

But we are still seeing type errors in code programmed against `WC_Session_Handler` when CoCart is active. 
In one of our plugins, we need to ensure the session is booted in a few areas that usually don't have a running checkout session - namely the `order-pay` feature. Initializing a session from scratch is not possible with `WC_Session` alone, so we have to typecheck against `WC_Session_Handler`. As soon as CoCart is added to the mix this code fails because we are receiving an incompatible object now.

`CoCart_Session_Handler` is [duck-type compatible](https://en.wikipedia.org/wiki/Duck_typing) (because it implements all the methods we need) but not _"strict-type compatible"_: We expect `B extends A` but receive `C extends A`

It is unfortunate that WooCommerce does not supply us with a common interface to sort out these type incompatibilities, so we're stuck between a rock and a hard place. Here's what we considered:

1. Loosen our type check, eg 
```php
                        assert(
                            $wcSession instanceof \WC_Session_Handler
                            || $wcSession instanceof \CoCart_Session_Handler
                        );
```
But that would introduce third-party-compat code right inside our core business logic which we would like to avoid

2. Add a basic duck-typing check, eg
```php
                        assert(
                            $wcSession instanceof \WC_Session_Handler
                            || count( array_intersect( [ /* 'has_session' etc. */ ], get_class_methods( $wcSession ) ) )
                        );
```
This would solve the issue of directly addressing third-party code and potentially avoid conflicts with other plugins that do the same. But it does not tell us if the method signatures are compatible. So our code could still fail and now we have less clear error messages

3. Ask you if you would consider subclassing `WC_Session_Handler` for maximum compatibility with the rest of the WooCommerce ecosystem. It seems to me that this would be the safest and cleanest solution, but it is out of my immediate control unfortunately :)

What do you think of the situation?

**Comment by seb86** [comment]
@Biont This is more of a [developers discussion](https://github.com/co-cart/co-cart/discussions/new) that would help all who are trying to support their code for such in depth compatibility. If you could [create a new discussion](https://github.com/co-cart/co-cart/discussions/new) instead, that would be a great start.

**Comment by Biont** [comment]
@seb86 Thank you for the suggestion. However, my intention was not to provide assistance for integrating with CoCart, but rather to suggest a change in your code - illustrated by the alternatives we considered so you understand I am not blindly requesting changes without doing my homework.

Would you please consider subclassing `WC_Session_Handler` for maximum compatibility with the rest of the WooCommerce ecosystem?

**Comment by seb86** [comment]
@Biont There is a reason for why CoCart uses it's own session handler. As I said this is more of a discussion or at least it's own issue so please create either to continue the conversation on this subject. Thank you.

**Comment by seb86** [comment]
Closing this issue as it got mixed with unrelated issues. Will start a new if needed.
