### ISSUE TITLE
Cart Item Not Getting updated, sends a success msg but It didn't updated on database

### ISSUE THREAD

**Issue by heshaShawky** [co-cart/co-cart#88]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of CoCart on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [ x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Sending a post request to `wp-json/cocart/v1/item ` with `cart_item_key ` and `quantity`
2. getting a success message that quantity has been update
3. after refresh for new data getting same old data without the qty updated
4. the bug only happens if I didn't set refresh_totals

## Expected/actual behaviour

I was expecting to see my cart item get qty updated as it should

**Comment by seb86** [comment]
Thats not a bug with CoCart. Its just the way it is in the core if WooCommerce because normally on the front end of the site they have JS that is triggered to update the totals. Its odd I know but I have switched the variable to true by default in the coming release for a better  experience. For now you will have to set the refresh_totals parameter to true yourself.
